budget/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('dashboard.urls')),
    path('categories/', include('categories.urls')),
    path('import/', include('import_data.urls')),
    path('operations/', include('operations.urls')),
    path('admin/', admin.site.urls),
]

categories/urls.py
from django.urls import path
from categories import views

app_name = 'categories'

urlpatterns = [
    path('types/', views.TypeListView.as_view(), name='types'),
    path('categories/', views.CategoryListView.as_view(), name='categories'),
    path('mcc/', views.MerchantCodeListView.as_view(), name='mcc'),
    path('descriptions/', views.DescriptionsView.as_view(), name='descriptions'),
]

dashboard/urls.py
from django.urls import path
from dashboard import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.Home.as_view(), name='index'),
    path('balance_check/', views.BalanceCheck.as_view(), name='balance_check'),
    path('balance/', views.BalanceView.as_view(), name='balance'),
    path('balance_demo/', views.myFirstChart, name='balance_demo'),
]

import_data/urls.py
from django.urls import path
from import_data import views

app_name = 'import_data'

urlpatterns = [
    path('', views.ImportCsvView.as_view(), name='import_csv'),
]

operations/urls.py
from django.urls import path
from operations import views

app_name = 'operations'

urlpatterns = [
    path('', views.OperationsView.as_view(), name='operations'),
]

templates/index.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">

    <link rel="stylesheet" href="{% static 'bootstrap-4.4.1-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'jquery/jquery-ui-themes-1.12.1/themes/base/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/budget.css' %}">
    {% block styles %}{% endblock %}

    <script src="{% static 'jquery/jquery-3.5.0.min.js' %}"></script>
    <script src="{% static 'jquery/jquery-ui-1.12.1/jquery-ui.min.js' %}"></script>
    <script src="{% static 'bootstrap-4.4.1-dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
    {% block scripts %}{% endblock %}

    <title>{% block title %} Budget {% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'dashboard:index' %}">Budget</a>
    <div class="navbar-nav">
        <div class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownBalance" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Balance
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownBalance">
              <a class="dropdown-item" href="{% url 'dashboard:balance_check' %}">Balance Check</a>
              <a class="dropdown-item" href="{% url 'dashboard:balance' %}">Balance</a>
            </div>
        </div>
        <a class="nav-item nav-link" href="{% url 'operations:operations' %}">Operations</a>
        <a class="nav-item nav-link" href="{% url 'import_data:import_csv' %}">Import</a>
        <div class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Categories
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'categories:categories' %}">Categories</a>
              <a class="dropdown-item" href="{% url 'categories:types' %}">Types</a>
              <a class="dropdown-item" href="{% url 'categories:mcc' %}">Merchant Codes</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'categories:descriptions' %}">Descriptions</a>
            </div>
        </div>
        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
    </div>
    </nav>
    <h4 class="pageHeader">{% block content-title %}{% endblock %}</h4>
    {% block content %}

    {% endblock %}
</body>
</html>

templates/object_confirm_delete.html
<div class="modal fade" id="deleteObjectModal" tabindex="-1" role="dialog" aria-labelledby="deleteObjectModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteObjectModalLabel">Deleting {{ model_name }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Do you really want to delete the {{ model_name }}?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Nope</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal" id="deleteObjectModalButton">Delete</button>
            </div>
        </div>
    </div>
</div>

templates/object_delete_with_replacement.html
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Deleting {{ model_name }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Do you really want to delete the {{ model_name }}?</p>
                <div class="form-group row">
                    <label for="newObjectSelect" class="col-sm-6 col-form-label">Choose new {{ model_name }}</label>
                    <div class="col-sm-6">
                        <select class="form-control" id="newObjectSelect">
                            <option selected value> -- choose -- </option>
                            {% for object in object_list_full %}
                            <option value="{{ object.id }}">{{ object.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Nope</button>
                <button type="button" class="btn btn-danger" id="deleteObjectModalButton" data-dismiss="modal">Delete</button>
            </div>
        </div>
    </div>
</div>